import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const [count, setCount] = useState(0);

  function addOne() {
    setCount(count + 1);
  }

  function deleteOne() {
    if (count > 0) {
      setCount(count - 1);
    }
  }

  function reset() {
    setCount(count - count);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="content">
          <h1>Counter</h1>
          <div>
            <span>{count}</span>
          </div>
          <div className="btn_content">
            <button onClick={addOne}>Increment</button>
            <button onClick={deleteOne}>Decrement</button>
            <button onClick={reset}>Reset</button>
          </div>
        </div>
      </main>
    </>
  );
}
